#!/bin/sh
base_dir='/tmp/user_notify'
trigger='false'

SCRIPTNAME="$(basename "$0")"
USAGE="Usage:
    $SCRIPTNAME [-t] [-d base_dir] -s (restart|error|update|news) 'msg_cz' 'msg_en'

    Create Foris notification

    Arguments:
        -t      Send notification immediately (triggers notifier script)
        -b base_dir
                Directory for notifications (defaults to '$base_dir')
        -s (restart|error|update|news)
                Type of a notification message
        msg_cz
                Notification text in Czech
        msg_en
                Notification text in English
"


if [ "$1" = -t ] ; then
	trigger=true
	shift
fi

if [ "$1" = -d ] ; then
	base_dir="$2"
	shift 2
fi

if [ $# -eq 3 ]; then
	compat=true
elif [ $# -ne 4 ]; then
	echo "$USAGE" >&2
	exit 1
else
	compat=false
fi

if [ "$1" = "-s" ]; then
	if [ "$2" = "restart" ] || [ "$2" = "error" ] || [ "$2" = "update" ] || [ "$2" = "news" ] ; then
		severity="$2"
	else
		echo "$USAGE" >&2
		exit 1
	fi
else
	echo "$USAGE" >&2
	exit 1
fi

message_cs="$3"
message_en="$4"
# This should be unique
msg_id="$(/bin/busybox date +%s)-$$"

if $compat; then
	export LANG="$(uci -q get foris.settings.lang)"
	export LANGUAGE="$LANG"
	[ -n "$GETTEXT_DOMAIN" ] || export GETTEXT_DOMAIN="user-notify"
fi

mkdir -p "$base_dir"
mkdir "$base_dir/tmp.$msg_id"
echo "$severity" > "$base_dir/tmp.$msg_id/severity"
if $compat ; then
	if [ -x /usr/bin/gettext_filter ]; then
		echo "$message_cs" | gettext_filter > "$base_dir/tmp.$msg_id/message"
	else
		echo "$message_cs" > "$base_dir/tmp.$msg_id/message"
	fi
else
	echo "$message_cs" > "$base_dir/tmp.$msg_id/message_cs"
	echo "$message_en" > "$base_dir/tmp.$msg_id/message_en"
fi

mv "$base_dir/tmp.$msg_id" "$base_dir/$msg_id"

if [ -x /usr/bin/foris-notify-wrapper ]; then
	# count messages based on their severity
	total=$(ls -1 "$base_dir"/*-*/severity 2>/dev/null | wc -l)
	displayed=$(ls -1 "$base_dir"/*-*/displayed  2>/dev/null | wc -l)
	active=$(($total - $displayed))
	# run on background and close outputs to speed up cmd execution
	/usr/bin/foris-notify-wrapper -m router_notifications -a create "{\"severity\": \"$severity\", \"id\": \"$msg_id\", \"new_count\": $active}" 1>/dev/null 2>&1 &
fi

if $trigger ; then
	exec notifier -d "$base_dir"
fi
