#!/bin/sh
. /usr/share/libubox/jshn.sh


set -e

if [ "$1" = "-n" ] ; then
	interactive_param=""
	shift
else
	interactive_param="-i"
fi

base_dir=${1:-/tmp/user_notify}

export_notification() {
	local dir_path="$1"
	local displayed
	if [ -f "$dir_path"/displayed ] ; then
		local displayed="1"
	else
		local displayed="0"
	fi
	json_add_boolean displayed $displayed
	local severity="$(cat "$dir_path/severity")"
	json_add_string id "$(basename "$dir_path")"
	json_add_string severity "$(cat "$dir_path/severity")"

	# parse messages

	# special treatment for single language messages (considered as english)
	if [ -f "$dir_path"/message ]; then
		local default_en_msg="$(cat "$dir_path"/message)"
	fi

	local en_used="n"
	json_add_object messages
	for filepath in "$dir_path"/message_?? ; do
		[ ! -e "$filepath" ] && break
		local lang="$(basename "$filepath" | tail -c 3)"
		if [ "$lang" = "en" ]; then
			en_used="y"
		fi
		json_add_string "$lang" "$(cat "$filepath")"
	done
	if [ "$en_used" = "n" ]; then
		json_add_string en "${default_en_msg:-}"
	fi
	json_close_object
}


[ ! -e "$base_dir" ] && echo '{"notifications": []}' && exit  # dir doesn't exist

json_init
json_add_array notifications
for notification_dir in "$base_dir/"??????????-* ; do
	[ ! -e "${notification_dir}" ] && continue
	json_add_object
	export_notification "$notification_dir"
	json_close_object
done
json_close_array

jshn ${interactive_param} -w
